package fr.gardoll.ace.controller.tools.autosampler ;

import java.io.File ;

import javax.swing.JFileChooser ;
import javax.swing.filechooser.FileFilter ;

import org.apache.logging.log4j.LogManager ;
import org.apache.logging.log4j.Logger ;

import fr.gardoll.ace.controller.column.Colonne ;
import fr.gardoll.ace.controller.core.ControlPanel ;
import fr.gardoll.ace.controller.core.InitializationException ;
import fr.gardoll.ace.controller.core.Observer ;
import fr.gardoll.ace.controller.core.ParametresSession ;
import fr.gardoll.ace.controller.core.Utils ;
import fr.gardoll.ace.controller.ui.AbstractJPanelObserver ;

public class AutosamplerToolPanel extends AbstractJPanelObserver
    implements ControlPanel, Observer
{
  private static final long serialVersionUID = -3286878572452437372L ;
  
  private static final Logger _LOG = LogManager.getLogger(AutosamplerToolPanel.class.getName());

  private final AutosamplerToolControl _ctrl ;

  /**
   * Creates new form AutosamplerToolPanel
   */
  public AutosamplerToolPanel(AutosamplerToolControl ctrl)
  {
    super(ctrl);
    this._ctrl = ctrl;
    initComponents() ;
    initCustom();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints ;

    logPanel = new javax.swing.JPanel() ;
    logTextScrollPane = new javax.swing.JScrollPane() ;
    logTextArea = new javax.swing.JTextArea() ;
    buttonPanel = new javax.swing.JPanel() ;
    cancelButton = new javax.swing.JButton() ;
    pauseToggleButton = new javax.swing.JToggleButton() ;
    closeButton = new javax.swing.JButton() ;
    buttonFiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0),
        new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0)) ;
    carouselPanel = new javax.swing.JPanel() ;
    positionPanel = new javax.swing.JPanel() ;
    positionLabel = new javax.swing.JLabel() ;
    positionSpinner = new javax.swing.JSpinner() ;
    positionButton = new javax.swing.JButton() ;
    arrowPanel = new javax.swing.JPanel() ;
    leftButton = new javax.swing.JButton() ;
    rightButton = new javax.swing.JButton() ;
    manualPanel = new javax.swing.JPanel() ;
    manualButton = new javax.swing.JButton() ;
    armPanel = new javax.swing.JPanel() ;
    freePositionPanel = new javax.swing.JPanel() ;
    freePositionLabel = new javax.swing.JLabel() ;
    freePositionSpinner = new javax.swing.JSpinner() ;
    freePositionButton = new javax.swing.JButton() ;
    vibrationPanel = new javax.swing.JPanel() ;
    vibrationButton = new javax.swing.JButton() ;
    refPositionPanel = new javax.swing.JPanel() ;
    toTopStopLabel = new javax.swing.JLabel() ;
    toTopStopButton = new javax.swing.JButton() ;
    aboveColumnLabel = new javax.swing.JLabel() ;
    openFileChooserButton = new javax.swing.JButton() ;
    aboveColumnButton = new javax.swing.JButton() ;
    toTrashBinLabel = new javax.swing.JLabel() ;
    toTrashBinButton = new javax.swing.JButton() ;

    setLayout(new java.awt.GridBagLayout()) ;

    logPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Log",
        javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
        javax.swing.border.TitledBorder.DEFAULT_POSITION,
        new java.awt.Font("Lucida Grande", 0, 15))) ; // NOI18N
    logPanel.setLayout(new java.awt.GridBagLayout()) ;

    logTextScrollPane.setHorizontalScrollBarPolicy(
        javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS) ;
    logTextScrollPane.setVerticalScrollBarPolicy(
        javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS) ;

    logTextArea.setEditable(false) ;
    logTextArea.setColumns(20) ;
    logTextArea.setLineWrap(true) ;
    logTextArea.setRows(5) ;
    logTextArea.addMouseListener(new java.awt.event.MouseAdapter()
    {
      @Override
      public void mouseClicked(java.awt.event.MouseEvent evt)
      {
        logTextAreaMouseClicked(evt) ;
      }
    }) ;
    logTextScrollPane.setViewportView(logTextArea) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.ipadx = 221 ;
    gridBagConstraints.ipady = 61 ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    logPanel.add(logTextScrollPane, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 1 ;
    gridBagConstraints.gridwidth = 2 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    add(logPanel, gridBagConstraints) ;

    buttonPanel.setLayout(new java.awt.GridBagLayout()) ;

    cancelButton.setText("cancel") ;
    cancelButton.addActionListener(new java.awt.event.ActionListener()
    {
      @Override
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        cancelButtonActionPerformed(evt) ;
      }
    }) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    buttonPanel.add(cancelButton, gridBagConstraints) ;

    pauseToggleButton.setText("pause") ;
    pauseToggleButton.addActionListener(new java.awt.event.ActionListener()
    {
      @Override
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        pauseToggleButtonActionPerformed(evt) ;
      }
    }) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 1 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    buttonPanel.add(pauseToggleButton, gridBagConstraints) ;

    closeButton.setText("close") ;
    closeButton.addActionListener(new java.awt.event.ActionListener()
    {
      @Override
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        closeButtonActionPerformed(evt) ;
      }
    }) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 3 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    buttonPanel.add(closeButton, gridBagConstraints) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 2 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    buttonPanel.add(buttonFiller, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 2 ;
    gridBagConstraints.gridwidth = 2 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    add(buttonPanel, gridBagConstraints) ;

    carouselPanel.setBorder(
        javax.swing.BorderFactory.createTitledBorder(null, "Carousel controls",
            javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
            javax.swing.border.TitledBorder.DEFAULT_POSITION,
            new java.awt.Font("Lucida Grande", 0, 15))) ; // NOI18N
    carouselPanel.setLayout(new java.awt.GridBagLayout()) ;

    positionPanel
        .setBorder(javax.swing.BorderFactory.createTitledBorder("Position")) ;
    positionPanel.setPreferredSize(new java.awt.Dimension(100, 50)) ;
    positionPanel.setLayout(new java.awt.GridBagLayout()) ;

    positionLabel.setText("position number") ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.gridwidth = 2 ;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    positionPanel.add(positionLabel, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 1 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    positionPanel.add(positionSpinner, gridBagConstraints) ;

    positionButton.setText("go") ;
    positionButton.setPreferredSize(new java.awt.Dimension(34, 26)) ;
    positionButton.addActionListener(new java.awt.event.ActionListener()
    {
      @Override
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        positionButtonActionPerformed(evt) ;
      }
    }) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 1 ;
    gridBagConstraints.gridy = 1 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    positionPanel.add(positionButton, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    carouselPanel.add(positionPanel, gridBagConstraints) ;

    arrowPanel.setBorder(
        javax.swing.BorderFactory.createTitledBorder("Quarter circle")) ;
    arrowPanel.setLayout(new java.awt.GridBagLayout()) ;

    leftButton.setText("<<") ;
    leftButton.addActionListener(new java.awt.event.ActionListener()
    {
      @Override
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        leftButtonActionPerformed(evt) ;
      }
    }) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    arrowPanel.add(leftButton, gridBagConstraints) ;

    rightButton.setText(">>") ;
    rightButton.addActionListener(new java.awt.event.ActionListener()
    {
      @Override
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        rightButtonActionPerformed(evt) ;
      }
    }) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 1 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    arrowPanel.add(rightButton, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 1 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    carouselPanel.add(arrowPanel, gridBagConstraints) ;

    manualPanel.setBorder(
        javax.swing.BorderFactory.createTitledBorder("Manual setting")) ;
    manualPanel.setLayout(new java.awt.GridBagLayout()) ;

    manualButton.setText("activate") ;
    manualButton.addActionListener(new java.awt.event.ActionListener()
    {
      @Override
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        manualButtonActionPerformed(evt) ;
      }
    }) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    manualPanel.add(manualButton, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 2 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    carouselPanel.add(manualPanel, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    add(carouselPanel, gridBagConstraints) ;

    armPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null,
        "Arm controls", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
        javax.swing.border.TitledBorder.DEFAULT_POSITION,
        new java.awt.Font("Lucida Grande", 0, 15))) ; // NOI18N
    armPanel.setLayout(new java.awt.GridBagLayout()) ;

    freePositionPanel.setBorder(
        javax.swing.BorderFactory.createTitledBorder("Free position")) ;
    freePositionPanel.setLayout(new java.awt.GridBagLayout()) ;

    freePositionLabel.setText("distance in millimeter") ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.gridwidth = 2 ;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    freePositionPanel.add(freePositionLabel, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 1 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    freePositionPanel.add(freePositionSpinner, gridBagConstraints) ;

    freePositionButton.setText("go") ;
    freePositionButton.addActionListener(new java.awt.event.ActionListener()
    {
      @Override
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        freePositionButtonActionPerformed(evt) ;
      }
    }) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 1 ;
    gridBagConstraints.gridy = 1 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    freePositionPanel.add(freePositionButton, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    armPanel.add(freePositionPanel, gridBagConstraints) ;

    vibrationPanel
        .setBorder(javax.swing.BorderFactory.createTitledBorder("Vibration")) ;
    vibrationPanel.setLayout(new java.awt.GridBagLayout()) ;

    vibrationButton.setText("activate") ;
    vibrationButton.addActionListener(new java.awt.event.ActionListener()
    {
      @Override
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        vibrationButtonActionPerformed(evt) ;
      }
    }) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    vibrationPanel.add(vibrationButton, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 1 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    armPanel.add(vibrationPanel, gridBagConstraints) ;

    refPositionPanel.setBorder(
        javax.swing.BorderFactory.createTitledBorder("Referenced position")) ;
    refPositionPanel.setLayout(new java.awt.GridBagLayout()) ;

    toTopStopLabel.setText("to top stop:") ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 1 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    refPositionPanel.add(toTopStopLabel, gridBagConstraints) ;

    toTopStopButton.setText("go") ;
    toTopStopButton.addActionListener(new java.awt.event.ActionListener()
    {
      @Override
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        toTopStopButtonActionPerformed(evt) ;
      }
    }) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 2 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    refPositionPanel.add(toTopStopButton, gridBagConstraints) ;

    aboveColumnLabel.setText("above column:") ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 1 ;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    refPositionPanel.add(aboveColumnLabel, gridBagConstraints) ;

    openFileChooserButton.setText("open") ;
    openFileChooserButton.addActionListener(new java.awt.event.ActionListener()
    {
      @Override
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        openFileChooserButtonActionPerformed(evt) ;
      }
    }) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 1 ;
    gridBagConstraints.gridy = 1 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    refPositionPanel.add(openFileChooserButton, gridBagConstraints) ;

    aboveColumnButton.setText("go") ;
    aboveColumnButton.addActionListener(new java.awt.event.ActionListener()
    {
      @Override
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        aboveColumnButtonActionPerformed(evt) ;
      }
    }) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 2 ;
    gridBagConstraints.gridy = 1 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    refPositionPanel.add(aboveColumnButton, gridBagConstraints) ;

    toTrashBinLabel.setText("to trash bin:") ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 1 ;
    gridBagConstraints.gridy = 2 ;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    refPositionPanel.add(toTrashBinLabel, gridBagConstraints) ;

    toTrashBinButton.setText("go") ;
    toTrashBinButton.addActionListener(new java.awt.event.ActionListener()
    {
      @Override
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        toTrashBinButtonActionPerformed(evt) ;
      }
    }) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 2 ;
    gridBagConstraints.gridy = 2 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    refPositionPanel.add(toTrashBinButton, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 2 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    armPanel.add(refPositionPanel, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 1 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    add(armPanel, gridBagConstraints) ;
  }// </editor-fold>

  private void positionButtonActionPerformed(java.awt.event.ActionEvent evt)
  {
    Integer position = null;
    try
    {
      this.positionSpinner.commitEdit();
      position = (Integer) this.positionSpinner.getValue();
    }
    catch(Exception e)
    {
      _LOG.error(String.format("error while fetching the position spinner value: %s", e.getMessage()));
      this.positionSpinner.setValue(0);
      return;
    }
    
    this._ctrl.carouselGoPosition(position);
  }

  private void leftButtonActionPerformed(java.awt.event.ActionEvent evt)
  {
    this._ctrl.carouselTurnLeft();
  }

  private void rightButtonActionPerformed(java.awt.event.ActionEvent evt)
  {
    this._ctrl.carouselTurnRight();
  }

  private void manualButtonActionPerformed(java.awt.event.ActionEvent evt)
  {
    this._ctrl.carouselFreeMove();
  }

  private void freePositionButtonActionPerformed(java.awt.event.ActionEvent evt)
  {
    Integer position = null;
    try
    {
      this.freePositionSpinner.commitEdit();
      position = (Integer) this.freePositionSpinner.getValue();
    }
    catch(Exception e)
    {
      _LOG.error(String.format("error while fetching the position spinner value: %s", e.getMessage()));
      this.freePositionSpinner.setValue(0);
      return;
    }
    
    this._ctrl.armFreeMove(position);
  }

  private void vibrationButtonActionPerformed(java.awt.event.ActionEvent evt)
  {
    this._ctrl.vibrate();
  }

  private void toTopStopButtonActionPerformed(java.awt.event.ActionEvent evt)
  {
    this._ctrl.armGoButee();
  }

  private void openFileChooserButtonActionPerformed(
      java.awt.event.ActionEvent evt)
  {
    int returnValue = fileChooser.showOpenDialog(this);
    if(returnValue == JFileChooser.APPROVE_OPTION)
    {
      File file = fileChooser.getSelectedFile().getAbsoluteFile();
      _LOG.info(String.format("selected column file: '%s'", file));
      try
      {
        this._ctrl.openColumn(file.toPath());
      }
      catch (InitializationException e)
      {
        String msg = "error while openning column file";
        _LOG.error(String.format("%s: %s", msg, e.getMessage()));
        this.handleException(msg, e);
      }
    }
    else
    {
      _LOG.debug("cancel column file openning");
    }
  }

  private void aboveColumnButtonActionPerformed(java.awt.event.ActionEvent evt)
  {
    this._ctrl.armGoColonne();
  }

  private void toTrashBinButtonActionPerformed(java.awt.event.ActionEvent evt)
  {
    this._ctrl.armGoTrash();
  }

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)
  {
    this.cancelAndReinit();
  }

  private void pauseToggleButtonActionPerformed(java.awt.event.ActionEvent evt)
  {
    this.pauseAndResume();
  }

  private void closeButtonActionPerformed(java.awt.event.ActionEvent evt)
  {
    this.close();
  }
  
  private void logTextAreaMouseClicked(java.awt.event.MouseEvent evt)
  {
    if(evt.getClickCount() == 2)
    {
      logTextArea.setText(null);
    }
  }

  // Variables declaration - do not modify
  private javax.swing.JButton aboveColumnButton ;
  private javax.swing.JLabel aboveColumnLabel ;
  private javax.swing.JPanel armPanel ;
  private javax.swing.JPanel arrowPanel ;
  private javax.swing.Box.Filler buttonFiller ;
  private javax.swing.JPanel buttonPanel ;
  private javax.swing.JButton cancelButton ;
  private javax.swing.JPanel carouselPanel ;
  private javax.swing.JButton closeButton ;
  private javax.swing.JButton freePositionButton ;
  private javax.swing.JLabel freePositionLabel ;
  private javax.swing.JPanel freePositionPanel ;
  private javax.swing.JSpinner freePositionSpinner ;
  private javax.swing.JButton leftButton ;
  private javax.swing.JPanel logPanel ;
  private javax.swing.JTextArea logTextArea ;
  private javax.swing.JScrollPane logTextScrollPane ;
  private javax.swing.JButton manualButton ;
  private javax.swing.JPanel manualPanel ;
  private javax.swing.JButton openFileChooserButton ;
  private javax.swing.JToggleButton pauseToggleButton ;
  private javax.swing.JButton positionButton ;
  private javax.swing.JLabel positionLabel ;
  private javax.swing.JPanel positionPanel ;
  private javax.swing.JSpinner positionSpinner ;
  private javax.swing.JPanel refPositionPanel ;
  private javax.swing.JButton rightButton ;
  private javax.swing.JButton toTopStopButton ;
  private javax.swing.JLabel toTopStopLabel ;
  private javax.swing.JButton toTrashBinButton ;
  private javax.swing.JLabel toTrashBinLabel ;
  private javax.swing.JButton vibrationButton ;
  private javax.swing.JPanel vibrationPanel ;
  // End of variables declaration                   

  private final JFileChooser fileChooser = new JFileChooser();
  
  private void initCustom()
  {
    this.fileChooser.setDialogTitle("select column file");
    this.fileChooser.setCurrentDirectory(ParametresSession.COLUMN_DIR_PATH.toFile());
    this.fileChooser.setMultiSelectionEnabled(false);
    this.fileChooser.setFileFilter(new FileFilter() 
    {
      @Override
      public boolean accept(File f)
      {
        if(f.isDirectory())
        {
          return true;
        }
        else
        {
          String fileName = f.getName();
          String file_extention = Utils.getFileExtention(fileName);
          return Colonne.COLUMN_FILE_EXTENTION.equals(file_extention);
        }
      }

      @Override
      public String getDescription()
      {
        return String.format("column file *.%s", Colonne.COLUMN_FILE_EXTENTION);
      }
    });
  }
  
  @Override
  protected void displayToUserLogSys(String msg)
  {
    this.logTextArea.append(msg);
  }
  
  @Override
  public void enableCloseControl(boolean isEnable)
  {
    closeButton.setEnabled(isEnable);
  }

  @Override
  public void enablePauseControl(boolean isEnable)
  {
    pauseToggleButton.setEnabled(isEnable || AutosamplerToolPanel.this._isResumeEnable);
    
    if(isEnable)
    {
      pauseToggleButton.setText("pause");
    }
    else
    {
      pauseToggleButton.setText("resume");
    }
  }

  @Override
  public void enableResumeControl(boolean isEnable)
  {
    pauseToggleButton.setEnabled(isEnable || AutosamplerToolPanel.this._isPauseEnable);
    
    if(isEnable)
    {
      pauseToggleButton.setText("resume");
    }
    else
    {
      pauseToggleButton.setText("pause");
    }
  }

  @Override
  public void enableCancelControl(boolean isEnable)
  {
    cancelButton.setEnabled(isEnable || AutosamplerToolPanel.this._isResumeEnable);
    
    if(isEnable)
    {
      cancelButton.setText("cancel");
    }
    else
    {
      cancelButton.setText("reset");
    }
  }

  @Override
  public void enableReinitControl(boolean isEnable)
  {
    cancelButton.setEnabled(isEnable || AutosamplerToolPanel.this._isCancelEnable);
    
    if(isEnable)
    {
      cancelButton.setText("reset");
    }
    else
    {
      cancelButton.setText("cancel");
    }
  }
  
  @Override
  public void enableStartControl(boolean isEnable)
  {
    aboveColumnButton.setEnabled(isEnable);
    freePositionButton.setEnabled(isEnable);
    leftButton.setEnabled(isEnable);
    manualButton.setEnabled(isEnable);
    openFileChooserButton.setEnabled(isEnable);
    positionButton.setEnabled(isEnable);
    rightButton.setEnabled(isEnable);
    toTopStopButton.setEnabled(isEnable);
    toTrashBinButton.setEnabled(isEnable);
    vibrationButton.setEnabled(isEnable);
  }
}