package fr.gardoll.ace.controller.core;

public enum ActionType
{
  ARM_MOVING,
  CAROUSEL_MOVING,
  CAROUSEL_RELATIVE_MOVING,
  ARM_END_MOVING,
  CAROUSEL_END_MOVING,
  WITHDRAWING,
  INFUSING,
  END,
  PAUSE, WAIT_PAUSE, RESUME,
  CANCEL, WAIT_CANCEL, REINIT, REINIT_DONE;
}
