package fr.gardoll.ace.controller.core;

public enum ActionType
{
  ARM_MOVING,
  CAROUSEL_MOVING,
  CAROUSEL_RELATIVE_MOVING,
  ARM_END_MOVING,
  CAROUSEL_END_MOVING,
  WITHDRAWING,
  INFUSING,
  PAUSING, WAIT_PAUSE, PAUSE_DONE,
  RESUME, RESUME_DONE,
  CANCELING, WAIT_CANCEL, CANCEL_DONE,
  REINIT, REINIT_DONE,
  OPEN_VALVE, CLOSE_VALVES, CLOSE_ALL_VALVES,
  CLOSING, USR_MSG, DRAIN_PUMP,
  BEGIN_SEQUENCE, SEQUENCE_AWAIT, SEQUENCE_AWAIT_DONE,
  H2O_RINCE, REFILL_PUMP, RINCE, SEQUENCE_PAUSE, END_SESSION;
}
