package fr.gardoll.ace.controller.tools.valves ;

import java.awt.event.AdjustmentEvent ;
import java.awt.event.AdjustmentListener ;

import javax.swing.ButtonModel ;
import javax.swing.text.DefaultCaret ;

import org.apache.logging.log4j.LogManager ;
import org.apache.logging.log4j.Logger ;

import fr.gardoll.ace.controller.core.ControlPanel ;
import fr.gardoll.ace.controller.ui.AbstractCloseableJPanelObserver ;

public class ValvesToolPanel extends AbstractCloseableJPanelObserver
    implements ControlPanel
{
  private static final long serialVersionUID = -8374471632745316066L ;

  private static final Logger _LOG = LogManager
      .getLogger(ValvesToolPanel.class.getName()) ;

  private final ValvesToolControl _ctrl ;
  
  private javax.swing.text.DefaultCaret caret;
  private javax.swing.BoundedRangeModel model;

  public ValvesToolPanel(ValvesToolControl ctrl)
  {
    super(ctrl) ;
    this._ctrl = ctrl ;
    initComponents() ;
    initCustom();
  }
  
  private void initCustom()
  {
    setupSmartScrolling();
  }
  
  private void setupSmartScrolling()
  {
    caret = (javax.swing.text.DefaultCaret) this.logTextArea.getCaret();
    
    javax.swing.JScrollBar scrollBar = this.logTextScrollPane.getVerticalScrollBar();
    model = scrollBar.getModel();
    scrollBar.addAdjustmentListener(new AdjustmentListener()
    {
      @Override
      public void adjustmentValueChanged(AdjustmentEvent e)
      {
        if (model.getValue() == model.getMaximum() - model.getExtent())
        {
           caret.setDot(logTextArea.getText().length());
           caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        }
        else
        {
           caret.setUpdatePolicy(DefaultCaret.NEVER_UPDATE);
        }
      }
    });
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints ;

    valveButtonGroup = new UnselectableButtonGroup() ;
    ValvesPanel = new javax.swing.JPanel() ;
    Valve1ToggleButton = new javax.swing.JToggleButton() ;
    Valve3ToggleButton = new javax.swing.JToggleButton() ;
    Valve5ToggleButton = new javax.swing.JToggleButton() ;
    filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0),
        new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767)) ;
    SwitchValveToggleButton = new javax.swing.JToggleButton() ;
    filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0),
        new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767)) ;
    Valve2ToggleButton = new javax.swing.JToggleButton() ;
    Valve4ToggleButton = new javax.swing.JToggleButton() ;
    Valve6ToggleButton = new javax.swing.JToggleButton() ;
    logPanel = new javax.swing.JPanel() ;
    logTextScrollPane = new javax.swing.JScrollPane() ;
    logTextArea = new javax.swing.JTextArea() ;
    buttonPanel = new javax.swing.JPanel() ;
    closeButton = new javax.swing.JButton() ;
    buttonFiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0),
        new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0)) ;

    setLayout(new java.awt.GridBagLayout()) ;

    ValvesPanel
        .setBorder(javax.swing.BorderFactory.createTitledBorder("Valves")) ;
    ValvesPanel.setLayout(new java.awt.GridBagLayout()) ;

    valveButtonGroup.add(Valve1ToggleButton) ;
    Valve1ToggleButton.setText("VALVE 1") ;
    Valve1ToggleButton.addActionListener(new java.awt.event.ActionListener()
    {
      @Override
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        Valve1ToggleButtonActionPerformed(evt) ;
      }
    }) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    ValvesPanel.add(Valve1ToggleButton, gridBagConstraints) ;

    valveButtonGroup.add(Valve3ToggleButton) ;
    Valve3ToggleButton.setText("VALVE 3") ;
    Valve3ToggleButton.addActionListener(new java.awt.event.ActionListener()
    {
      @Override
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        Valve3ToggleButtonActionPerformed(evt) ;
      }
    }) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 1 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    ValvesPanel.add(Valve3ToggleButton, gridBagConstraints) ;

    valveButtonGroup.add(Valve5ToggleButton) ;
    Valve5ToggleButton.setText("VALVE 5") ;
    Valve5ToggleButton.addActionListener(new java.awt.event.ActionListener()
    {
      @Override
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        Valve5ToggleButtonActionPerformed(evt) ;
      }
    }) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 2 ;
    gridBagConstraints.gridy = 2 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    ValvesPanel.add(Valve5ToggleButton, gridBagConstraints) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 1 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    ValvesPanel.add(filler1, gridBagConstraints) ;

    valveButtonGroup.add(SwitchValveToggleButton) ;
    SwitchValveToggleButton.setText("SWITCH VALVE") ;
    SwitchValveToggleButton
        .addActionListener(new java.awt.event.ActionListener()
        {
          @Override
          public void actionPerformed(java.awt.event.ActionEvent evt)
          {
            SwitchValveToggleButtonActionPerformed(evt) ;
          }
        }) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 1 ;
    gridBagConstraints.gridy = 1 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    ValvesPanel.add(SwitchValveToggleButton, gridBagConstraints) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 2 ;
    gridBagConstraints.gridy = 1 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    ValvesPanel.add(filler2, gridBagConstraints) ;

    valveButtonGroup.add(Valve2ToggleButton) ;
    Valve2ToggleButton.setText("VALVE 2") ;
    Valve2ToggleButton.addActionListener(new java.awt.event.ActionListener()
    {
      @Override
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        Valve2ToggleButtonActionPerformed(evt) ;
      }
    }) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 2 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    ValvesPanel.add(Valve2ToggleButton, gridBagConstraints) ;

    valveButtonGroup.add(Valve4ToggleButton) ;
    Valve4ToggleButton.setText("VALVE 4") ;
    Valve4ToggleButton.addActionListener(new java.awt.event.ActionListener()
    {
      @Override
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        Valve4ToggleButtonActionPerformed(evt) ;
      }
    }) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 1 ;
    gridBagConstraints.gridy = 2 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    ValvesPanel.add(Valve4ToggleButton, gridBagConstraints) ;

    valveButtonGroup.add(Valve6ToggleButton) ;
    Valve6ToggleButton.setText("VALVE 6") ;
    Valve6ToggleButton.addActionListener(new java.awt.event.ActionListener()
    {
      @Override
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        Valve6ToggleButtonActionPerformed(evt) ;
      }
    }) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 2 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    ValvesPanel.add(Valve6ToggleButton, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    add(ValvesPanel, gridBagConstraints) ;

    logPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Log",
        javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
        javax.swing.border.TitledBorder.DEFAULT_POSITION,
        new java.awt.Font("Lucida Grande", 0, 15))) ; // NOI18N
    logPanel.setLayout(new java.awt.GridBagLayout()) ;

    logTextScrollPane.setHorizontalScrollBarPolicy(
        javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS) ;
    logTextScrollPane.setVerticalScrollBarPolicy(
        javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS) ;

    logTextArea.setEditable(false) ;
    logTextArea.setColumns(20) ;
    logTextArea.setLineWrap(true) ;
    logTextArea.setRows(5) ;
    logTextScrollPane.setViewportView(logTextArea) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.ipadx = 221 ;
    gridBagConstraints.ipady = 61 ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    logPanel.add(logTextScrollPane, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 1 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    add(logPanel, gridBagConstraints) ;

    buttonPanel.setLayout(new java.awt.GridBagLayout()) ;

    closeButton.setText("close") ;
    closeButton.addActionListener(new java.awt.event.ActionListener()
    {
      @Override
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        closeButtonActionPerformed(evt) ;
      }
    }) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 3 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    buttonPanel.add(closeButton, gridBagConstraints) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 2 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    buttonPanel.add(buttonFiller, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 2 ;
    gridBagConstraints.gridwidth = 2 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    add(buttonPanel, gridBagConstraints) ;
  }// </editor-fold>//GEN-END:initComponents

  private void closeButtonActionPerformed(java.awt.event.ActionEvent evt)
  {// GEN-FIRST:event_closeButtonActionPerformed
    _LOG.debug("**** event close ****");
    this.close();
  }// GEN-LAST:event_closeButtonActionPerformed

  private void Valve1ToggleButtonActionPerformed(java.awt.event.ActionEvent evt)
  {// GEN-FIRST:event_Valve1ToggleButtonActionPerformed
    _LOG.debug("**** event valve 1 ****");
    this._ctrl.handleValve(1);
  }// GEN-LAST:event_Valve1ToggleButtonActionPerformed

  private void Valve3ToggleButtonActionPerformed(java.awt.event.ActionEvent evt)
  {// GEN-FIRST:event_Valve3ToggleButtonActionPerformed
    _LOG.debug("**** event valve 3 ****");
    this._ctrl.handleValve(3);
  }// GEN-LAST:event_Valve3ToggleButtonActionPerformed

  private void Valve6ToggleButtonActionPerformed(java.awt.event.ActionEvent evt)
  {// GEN-FIRST:event_Valve6ToggleButtonActionPerformed
    _LOG.debug("**** event valve 6 ****");
    this._ctrl.handleValve(6);
  }// GEN-LAST:event_Valve6ToggleButtonActionPerformed

  private void SwitchValveToggleButtonActionPerformed(
      java.awt.event.ActionEvent evt)
  {// GEN-FIRST:event_SwitchValveToggleButtonActionPerformed
    _LOG.debug("**** event valve 7 ****");
    this._ctrl.handleValve(7);
  }// GEN-LAST:event_SwitchValveToggleButtonActionPerformed

  private void Valve2ToggleButtonActionPerformed(java.awt.event.ActionEvent evt)
  {// GEN-FIRST:event_Valve2ToggleButtonActionPerformed
    _LOG.debug("**** event valve 2 ****");
    this._ctrl.handleValve(2);
  }// GEN-LAST:event_Valve2ToggleButtonActionPerformed

  private void Valve4ToggleButtonActionPerformed(java.awt.event.ActionEvent evt)
  {// GEN-FIRST:event_Valve4ToggleButtonActionPerformed
    _LOG.debug("**** event valve 4 ****");
    this._ctrl.handleValve(4);
  }// GEN-LAST:event_Valve4ToggleButtonActionPerformed

  private void Valve5ToggleButtonActionPerformed(java.awt.event.ActionEvent evt)
  {// GEN-FIRST:event_Valve5ToggleButtonActionPerformed
    _LOG.debug("**** event valve 5 ****");
    this._ctrl.handleValve(5);
  }// GEN-LAST:event_Valve5ToggleButtonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JToggleButton SwitchValveToggleButton ;
  private javax.swing.JToggleButton Valve1ToggleButton ;
  private javax.swing.JToggleButton Valve2ToggleButton ;
  private javax.swing.JToggleButton Valve3ToggleButton ;
  private javax.swing.JToggleButton Valve4ToggleButton ;
  private javax.swing.JToggleButton Valve5ToggleButton ;
  private javax.swing.JToggleButton Valve6ToggleButton ;
  private javax.swing.JPanel ValvesPanel ;
  private javax.swing.Box.Filler buttonFiller ;
  private javax.swing.JPanel buttonPanel ;
  private javax.swing.JButton closeButton ;
  private javax.swing.Box.Filler filler1 ;
  private javax.swing.Box.Filler filler2 ;
  private javax.swing.JPanel logPanel ;
  private javax.swing.JTextArea logTextArea ;
  private javax.swing.JScrollPane logTextScrollPane ;
  private UnselectableButtonGroup valveButtonGroup ;
  // End of variables declaration//GEN-END:variables

  @Override
  protected void displayToUserLogSys(String msg)
  {
    this.logTextArea.append(msg);
  }

  @Override
  protected void enableCloseControl(boolean isEnable)
  {
    this.closeButton.setEnabled(isEnable);
  }
}

class UnselectableButtonGroup extends javax.swing.ButtonGroup
{
  private static final long serialVersionUID = 5748377399340064727L ;

  @Override
  public void setSelected(ButtonModel model, boolean selected)
  {
    if(selected)
    {
      super.setSelected(model, selected) ;
    }
    else
    {
      this.clearSelection() ;
    }
  }
}
