package fr.gardoll.ace.controller.tools.settings.protocol ;

public class VolumeProtocolPanel extends javax.swing.JPanel
{

  private static final long serialVersionUID = 1401413721442111518L ;

  /**
   * Creates new form VolumeProtocolPanel
   */
  public VolumeProtocolPanel()
  {
    initComponents() ;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints ;

    protocolOpenPanel = new javax.swing.JPanel() ;
    openProtocolButton = new javax.swing.JButton() ;
    protocolTextField = new javax.swing.JTextField() ;
    nbColumnPanel = new javax.swing.JPanel() ;
    nbColumnSpinner = new javax.swing.JSpinner() ;
    volumePanel = new javax.swing.JPanel() ;
    volumeScrollPane = new javax.swing.JScrollPane() ;
    volumeTable = new javax.swing.JTable() ;

    setPreferredSize(new java.awt.Dimension(780, 460)) ;
    setLayout(new java.awt.GridBagLayout()) ;

    protocolOpenPanel
        .setBorder(javax.swing.BorderFactory.createTitledBorder("Protocol")) ;
    protocolOpenPanel.setLayout(new java.awt.GridBagLayout()) ;

    openProtocolButton.setText("open") ;
    openProtocolButton.addActionListener(new java.awt.event.ActionListener()
    {
      @Override
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        openProtocolButtonActionPerformed(evt) ;
      }
    }) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    protocolOpenPanel.add(openProtocolButton, gridBagConstraints) ;

    protocolTextField.setEditable(false) ;
    protocolTextField.setText("open protocol file") ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 1 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    protocolOpenPanel.add(protocolTextField, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 0.1 ;
    gridBagConstraints.weighty = 0.1 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    add(protocolOpenPanel, gridBagConstraints) ;

    nbColumnPanel.setBorder(
        javax.swing.BorderFactory.createTitledBorder("Number of columns")) ;
    nbColumnPanel.setLayout(new java.awt.GridBagLayout()) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    nbColumnPanel.add(nbColumnSpinner, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 1 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 0.1 ;
    gridBagConstraints.weighty = 0.1 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    add(nbColumnPanel, gridBagConstraints) ;

    volumePanel.setBorder(
        javax.swing.BorderFactory.createTitledBorder("Volume in mL")) ;
    volumePanel.setLayout(new java.awt.GridBagLayout()) ;

    volumeTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][] { { null, null, null, null }, { null, null, null, null },
            { null, null, null, null }, { null, null, null, null } },
        new String[] { "Title 1", "Title 2", "Title 3", "Title 4" })) ;
    volumeScrollPane.setViewportView(volumeTable) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    volumePanel.add(volumeScrollPane, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 1 ;
    gridBagConstraints.gridwidth = 2 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    add(volumePanel, gridBagConstraints) ;
  }// </editor-fold>

  private void openProtocolButtonActionPerformed(java.awt.event.ActionEvent evt)
  {
    // TODO add your handling code here:
  }

  // Variables declaration - do not modify
  private javax.swing.JPanel nbColumnPanel ;
  private javax.swing.JSpinner nbColumnSpinner ;
  private javax.swing.JButton openProtocolButton ;
  private javax.swing.JPanel protocolOpenPanel ;
  private javax.swing.JTextField protocolTextField ;
  private javax.swing.JPanel volumePanel ;
  private javax.swing.JScrollPane volumeScrollPane ;
  private javax.swing.JTable volumeTable ;
  // End of variables declaration
}
