package fr.gardoll.ace.controller.settings ;

import java.util.ArrayList ;
import java.util.List ;

import fr.gardoll.ace.controller.core.ConfigurationException ;
import fr.gardoll.ace.controller.ui.TextFieldRealNumber ;

// TODO check syringe volume against rince volume.
public class GeneralPanel extends javax.swing.JPanel implements Panel
{
  private static final long serialVersionUID = -4086064621880324437L ;
  public static final String NAME = "general" ;
  private final List<TextFieldRealNumber> _realTextFields = new ArrayList<>();

  /**
   * Creates new form PumpPanel
   */
  public GeneralPanel()
  {
    initComponents() ;
    initCustom() ;
  }

  private void initCustom()
  {
    this.syringebuttonGroup.add(this.oneSyringeRadioButton) ;
    this.syringebuttonGroup.add(this.twoSyringeRadioButton) ;
    
    this._realTextFields.add(new TextFieldRealNumber("syringe volume",
                               this.syringeVolumeTextField,
                               0.,
                               100.));
    
    this._realTextFields.add(new TextFieldRealNumber("pump max rate",
                               this.pumpMaxRateTextField,
                               0.,
                               15.));
    
    this._realTextFields.add(new TextFieldRealNumber("rince volume",
                               this.rinceVolumeTextField,
                               0.,
                               100.));
    
    this._realTextFields.add(new TextFieldRealNumber("syringe diameter",
                               this.syringeDiameterTextField,
                               0.,
                               100.));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints ;

    syringebuttonGroup = new javax.swing.ButtonGroup() ;
    pumpSettingsPanel = new javax.swing.JPanel() ;
    pumpMaxRatePanel = new javax.swing.JPanel() ;
    pumpMaxRateTextField = new javax.swing.JTextField() ;
    pumpSyringePanel = new javax.swing.JPanel() ;
    oneSyringeRadioButton = new javax.swing.JRadioButton() ;
    twoSyringeRadioButton = new javax.swing.JRadioButton() ;
    rinceSettingsPanel = new javax.swing.JPanel() ;
    rinceVolumePanel = new javax.swing.JPanel() ;
    rinceVolumeTextField = new javax.swing.JTextField() ;
    rinceNumberPanel = new javax.swing.JPanel() ;
    rinceNumberSpinner = new javax.swing.JSpinner() ;
    syringeSettingsPanel = new javax.swing.JPanel() ;
    syringeDiameterPanel = new javax.swing.JPanel() ;
    syringeDiameterTextField = new javax.swing.JTextField() ;
    syringeVolumePanel = new javax.swing.JPanel() ;
    syringeVolumeTextField = new javax.swing.JTextField() ;
    miscSettingsPanel = new javax.swing.JPanel() ;
    miscModePanel = new javax.swing.JPanel() ;
    fullScreenModeCheckBox = new javax.swing.JCheckBox() ;
    debugModeCheckBox = new javax.swing.JCheckBox() ;

    setPreferredSize(new java.awt.Dimension(780, 460)) ;
    setLayout(new java.awt.GridBagLayout()) ;

    pumpSettingsPanel
        .setBorder(javax.swing.BorderFactory.createTitledBorder("Pump")) ;
    pumpSettingsPanel.setLayout(new java.awt.GridBagLayout()) ;

    pumpMaxRatePanel.setBorder(
        javax.swing.BorderFactory.createTitledBorder("Maximum rate (mL/min)")) ;
    pumpMaxRatePanel.setLayout(new java.awt.GridBagLayout()) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.ipadx = 70 ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    pumpMaxRatePanel.add(pumpMaxRateTextField, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    pumpSettingsPanel.add(pumpMaxRatePanel, gridBagConstraints) ;

    pumpSyringePanel.setBorder(
        javax.swing.BorderFactory.createTitledBorder("Number of syringe")) ;
    pumpSyringePanel.setLayout(new java.awt.GridBagLayout()) ;

    oneSyringeRadioButton.setText("one") ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    pumpSyringePanel.add(oneSyringeRadioButton, gridBagConstraints) ;

    twoSyringeRadioButton.setText("two") ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 1 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    pumpSyringePanel.add(twoSyringeRadioButton, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 1 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    pumpSettingsPanel.add(pumpSyringePanel, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    add(pumpSettingsPanel, gridBagConstraints) ;

    rinceSettingsPanel
        .setBorder(javax.swing.BorderFactory.createTitledBorder("Rincing")) ;
    rinceSettingsPanel.setLayout(new java.awt.GridBagLayout()) ;

    rinceVolumePanel.setBorder(
        javax.swing.BorderFactory.createTitledBorder("Volume (mL)")) ;
    rinceVolumePanel.setLayout(new java.awt.GridBagLayout()) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    rinceVolumePanel.add(rinceVolumeTextField, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    rinceSettingsPanel.add(rinceVolumePanel, gridBagConstraints) ;

    rinceNumberPanel.setBorder(
        javax.swing.BorderFactory.createTitledBorder("Number per cycle")) ;
    rinceNumberPanel.setLayout(new java.awt.GridBagLayout()) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    rinceNumberPanel.add(rinceNumberSpinner, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 1 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    rinceSettingsPanel.add(rinceNumberPanel, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 1 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    add(rinceSettingsPanel, gridBagConstraints) ;

    syringeSettingsPanel
        .setBorder(javax.swing.BorderFactory.createTitledBorder("Syringe")) ;
    syringeSettingsPanel.setLayout(new java.awt.GridBagLayout()) ;

    syringeDiameterPanel.setBorder(
        javax.swing.BorderFactory.createTitledBorder("Diameter (mm)")) ;
    syringeDiameterPanel.setToolTipText("") ;
    syringeDiameterPanel.setLayout(new java.awt.GridBagLayout()) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.ipadx = 70 ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    syringeDiameterPanel.add(syringeDiameterTextField, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    syringeSettingsPanel.add(syringeDiameterPanel, gridBagConstraints) ;

    syringeVolumePanel.setBorder(
        javax.swing.BorderFactory.createTitledBorder("Volume (mL)")) ;
    syringeVolumePanel.setLayout(new java.awt.GridBagLayout()) ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    syringeVolumePanel.add(syringeVolumeTextField, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 1 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    syringeSettingsPanel.add(syringeVolumePanel, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 1 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    add(syringeSettingsPanel, gridBagConstraints) ;

    miscSettingsPanel.setBorder(
        javax.swing.BorderFactory.createTitledBorder("Miscellaneous")) ;
    miscSettingsPanel.setLayout(new java.awt.GridBagLayout()) ;

    miscModePanel
        .setBorder(javax.swing.BorderFactory.createTitledBorder("Modes")) ;
    miscModePanel.setLayout(new java.awt.GridBagLayout()) ;

    fullScreenModeCheckBox.setText("full screen mode") ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 0 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.ipadx = 46 ;
    gridBagConstraints.ipady = 39 ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    miscModePanel.add(fullScreenModeCheckBox, gridBagConstraints) ;

    debugModeCheckBox.setText("debug mode") ;
    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 0 ;
    gridBagConstraints.gridy = 1 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.ipadx = 73 ;
    gridBagConstraints.ipady = 39 ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    miscModePanel.add(debugModeCheckBox, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    miscSettingsPanel.add(miscModePanel, gridBagConstraints) ;

    gridBagConstraints = new java.awt.GridBagConstraints() ;
    gridBagConstraints.gridx = 1 ;
    gridBagConstraints.gridy = 1 ;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH ;
    gridBagConstraints.weightx = 1.0 ;
    gridBagConstraints.weighty = 1.0 ;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2) ;
    add(miscSettingsPanel, gridBagConstraints) ;
  }// </editor-fold>

  // Variables declaration - do not modify
  private javax.swing.JCheckBox debugModeCheckBox ;
  private javax.swing.JCheckBox fullScreenModeCheckBox ;
  private javax.swing.JPanel miscModePanel ;
  private javax.swing.JPanel miscSettingsPanel ;
  private javax.swing.JRadioButton oneSyringeRadioButton ;
  private javax.swing.JPanel pumpMaxRatePanel ;
  private javax.swing.JTextField pumpMaxRateTextField ;
  private javax.swing.JPanel pumpSettingsPanel ;
  private javax.swing.JPanel pumpSyringePanel ;
  private javax.swing.JPanel rinceNumberPanel ;
  private javax.swing.JSpinner rinceNumberSpinner ;
  private javax.swing.JPanel rinceSettingsPanel ;
  private javax.swing.JPanel rinceVolumePanel ;
  private javax.swing.JTextField rinceVolumeTextField ;
  private javax.swing.JPanel syringeDiameterPanel ;
  private javax.swing.JTextField syringeDiameterTextField ;
  private javax.swing.JPanel syringeSettingsPanel ;
  private javax.swing.JPanel syringeVolumePanel ;
  private javax.swing.JTextField syringeVolumeTextField ;
  private javax.swing.ButtonGroup syringebuttonGroup ;
  private javax.swing.JRadioButton twoSyringeRadioButton ;
  // End of variables declaration

  @Override
  public void save()  throws ConfigurationException
  {
    // TODO Auto-generated method stub
    
  }

  @Override
  public String getPanelName()
  {
    return GeneralPanel.NAME;
  }
}
